exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('sheet').del()
    .then(function () {
      // Inserts seed entries
      return knex('sheet').insert([{
        id:1,
        users_id: 1,
        char_name: "Hantas Yurtbane",
        char_class: "Shaman",
        char_size: "M",
        char_align: "CG",
        char_race: "Half-Elf",
        char_weight: "185 lbs",
        char_age: 25,
        char_height: "6 feet",
        char_gender: "Male",
        char_languages: "Hallit, Common, Celestial",
        char_level: 17,
        initative: 4,
        sr: 5,
        dr: 10,
        speed: 30,
        strength: 10,
        dexterity: 12,
        constution: 14,
        intellect: 12,
        wisdom: 22,
        charisma: 8,
        bab_1: 17,
        bab_2: 12,
        bab_3: 7,
        bab_4: 2,
        cmb: 12,
        cmd: 24,
        max_hp: 155,
        current_hp: 85,
        armor_class: 24,
        fortitude: 11,
        reflex: 8,
        will: 15
      },
      {
        id:2,
        users_id: 1,
        char_name: "Reynold Ironflag",
        char_class: "Cleric",
        char_size: "M",
        char_align: "CG",
        char_race: "Dwarf",
        char_weight: "185 lbs",
        char_age: 55,
        char_height: "4 feet 11 inches",
        char_gender: "Male",
        char_languages: "Dwarven, Common, Arcadian",
        char_level: 9,
        initative: 4,
        sr: 0,
        dr: 0,
        speed: 30,
        strength: 22,
        dexterity: 12,
        constution: 18,
        intellect: 10,
        wisdom: 25,
        charisma: 14,
        bab_1: 7,
        bab_2: 2,
        bab_3: 0,
        bab_4: 0,
        cmb: 12,
        cmd: 24,
        max_hp: 99,
        current_hp: 99,
        armor_class: 18,
        fortitude: 11,
        reflex: 8,
        will: 15
      },
      {
        id:3,
        users_id: 1,
        char_name: "Santo Mistico",
        char_class: "Brawler",
        char_size: "M",
        char_align: "NE",
        char_race: "Oread",
        char_weight: "220 lbs",
        char_age: 25,
        char_height: "6 feet",
        char_gender: "Male",
        char_languages: "Common, Infernal, Aklo",
        char_level: 11,
        initative: 4,
        sr: 5,
        dr: 10,
        speed: 30,
        strength: 23,
        dexterity: 16,
        constution: 14,
        intellect: 10,
        wisdom: 12,
        charisma: 7,
        bab_1: 17,
        bab_2: 12,
        bab_3: 7,
        bab_4: 2,
        cmb: 12,
        cmd: 24,
        max_hp: 155,
        current_hp: 88,
        armor_class: 21,
        fortitude: 11,
        reflex: 11,
        will: 7
      }])
      .then(() => {
        return knex.raw("SELECT setval('sheet_id_seq',(SELECT MAX(id) FROM sheet));")
      })
    })
}
